### ISSUE TITLE
Build error on missing namespace

### ISSUE THREAD

**Issue by rogeralsing** [StefH/ProxyInterfaceSourceGenerator#42]
If the Interface with the proxy attribute is defined in a file without a namespace. this results in a build error as the generated 
e.g.

``` c#
using Akka.Actor;

//namespace ConsoleApp66;  <- no namespace

[ProxyInterfaceGenerator.Proxy(typeof(LocalActorRefProvider))]
public partial interface ILocalActorRefProvider
{
}
```

code ends up looking like so:

``` c#
namespace.  /*nothing here*/
{
// all the proxy stuff


}
```

**Comment by StefH** [comment]
Should be fixed in
https://github.com/StefH/ProxyInterfaceSourceGenerator/pull/46
