### ISSUE TITLE
Proxy does only proxy top level members

### ISSUE THREAD

**Issue by rogeralsing** [StefH/ProxyInterfaceSourceGenerator#43]
If you proxy a subtype of any kind. only the methods in the subtype is proxied. no visible members from the base type(s) are part of the generated code.

e.g.

``` c#
public class A 
{
    void Foo() {}
}

public class B : A 
{
     void Bar() {}
}

[ProxyInterfaceGenerator.Proxy(typeof(B))]
public partial interface IB {
}

```

The proxy will only contain code for `Bar`, nothing for `Foo`

**Comment by StefH** [comment]
The 'work around' for this is to proxy both classes:
``` c#
[ProxyInterfaceGenerator.Proxy(typeof(A))]
public partial interface IA {
}

[ProxyInterfaceGenerator.Proxy(typeof(B))]
public partial interface IB : IA {
}
```

And example like this is:
- https://github.com/StefH/ProxyInterfaceSourceGenerator/blob/main/src-examples/ProxyInterfaceConsumerForPnP/Interfaces/IClientObject.cs
- https://github.com/StefH/ProxyInterfaceSourceGenerator/blob/main/src-examples/ProxyInterfaceConsumerForPnP/Interfaces/ISecurableObject.cs

**Comment by StefH** [comment]
@rogeralsing 
Actually, this should work like this : https://github.com/StefH/ProxyInterfaceSourceGenerator#proxybaseclasses

**Comment by StefH** [comment]
@rogeralsing 
Does this answer you question?

**Comment by StefH** [comment]
@rogeralsing
Is this enough information for you?
