### ISSUE TITLE
Proxy interfaces should work?

### ISSUE THREAD

**Issue by rogeralsing** [StefH/ProxyInterfaceSourceGenerator#45]
Maybe this is out of scope, but the same way as you proxy to a class. it would be useful to be able to proxy to an interface

```csharp
public interface IA
{
    void Foo();
}

public class A:IA 
{
   public void Foo() {}
}

[ProxyInterfaceGenerator.Proxy(typeof(A))] // this works
public partial interface IADecorator{
}

[ProxyInterfaceGenerator.Proxy(typeof(IA))] // this does not
public partial interface IIADecorator{
}

```

maybe I'm brainfarting here, but I think it should be pretty much the same, as the instance is provided to the proxy from the outside.

**Comment by StefH** [comment]
I wonder what the usecase would be to generate a interface + proxy from an interface?
