### ISSUE TITLE
Proxied array return types are left as is, and do not return their proxied type

### ISSUE THREAD

**Issue by FatSwords** [StefH/ProxyInterfaceSourceGenerator#52]
Hi,

This is an awesome project, which is going to save me a ton of time.  I have a 3rd party library I can't modify to work with which is basically untestable and contains thousands of types, and the idea of manually proxying them all is awful.

I have one issue I don't seem able to solve.  I have a type in the third part library which works like this
``` c#
public class Foo
{
    public Bar DoSomethingAndGetABar()
    public Bar[] DoSomethingAndGetAnArrayOfBars()
}
```
If I proxy both foo and bar, my IFoo.DoSomethingAndGetABar() returns IBar, as expected, but IFoo.DosomethingAndGetAnArrayOfBars() returns []Bar, not []IBar.

In here:

https://github.com/StefH/ProxyInterfaceSourceGenerator/blob/541477b545ea591ac07024221cc7c683f50bf4b2/src-examples/ProxyInterfaceConsumerViaNuGet/Person.cs

You test List<Address>, and replacing that with []Address doesn't get mapped.  I'll have a quick bash at fixing it and show my fix if I get something working

**Comment by StefH** [comment]
This class:
``` c#
public class Foo
{
    public Bar DoSomethingAndGetABar()
    {
        return new Bar();
    }

    public Bar[] DoSomethingAndGetAnArrayOfBars()
    {
        return new[] { new Bar() };
    }

    public Foo DoSomethingAndGetAFoo()
    {
        return new Foo();
    }

    public Foo[] DoSomethingAndGetAnArrayOfFoos()
    {
        return new[] { new Foo() };
    }
}

**Comment by StefH** [comment]
https://github.com/StefH/ProxyInterfaceSourceGenerator/pull/53

**Comment by StefH** [comment]
@FatSwords 
I did fix it, please see the https://github.com/StefH/ProxyInterfaceSourceGenerator/pull/53 for details.
