### ISSUE TITLE
Parameters passed in with Keyword "ref" are proxied such that they are no longer updated by reference

### ISSUE THREAD

**Issue by FatSwords** [StefH/ProxyInterfaceSourceGenerator#60]
Given a method I am trying to proxy

`public class Foo
{
public void DoAThing(int a, ref int b)
{
b=b+a;
}
}`

I'll get a proxy class

`public FooProxy : IFoo
{
public void DoAThing(int a, ref int b)
{
int a_ = a;
int b_ = b;
_Instance.DoAThing(a_, b_);
}
}`

This results in us updating the value of b_, not b, so expected behavior of the by ref passing isn't maintained.

**Comment by StefH** [comment]
I did change the generator so that this code:
``` c#
public void In_Out_Ref1(in int a, out int b, ref int c)
        {
            b = 1;
            c++;
        }
```

And proxy code will be 
``` c#
public void In_Out_Ref1(in int a, out int b, ref int c)
        {
            int b_;
            _Instance.In_Out_Ref1(in a, out b_, ref c);
            b = b_;
        }
```

This should be ok, correct?

**Comment by FatSwords** [comment]
that certainly looks correct to me - thanks as ever for the quick response!

**Comment by StefH** [comment]
a new nuget will be released shorty
