### ISSUE TITLE
Is there a way we can lazy load interface mappings?

### ISSUE THREAD

**Issue by JROBOTO** [StefH/ProxyInterfaceSourceGenerator#74]
Some of the objects we are attempting to map can be quite big however we rarely need every property of every bit. Would it be possible to adapt the functionality so that, internally, we only map the property of the instance to its interface if that interface is called upon? I have a function I am calling where the API takes 0.08 seconds however the resulting mapping takes ~1 minute for 12000 items in the resulting collection.

For example:
If I have object
``` c#
public class Thing
{
    public OtherObject SubThing { get; }
}
```
If I had a function returning the mapped `IThing`, the `SubThing` property would not be mapped until I explicitly asked for it.

Purely hypothetical of course

**Comment by StefH** [comment]
@JROBOTO 
At this moment when I have these classes:
``` c#
public class Person : Human
{
  public Human Human { get; set; }
}

public class Human
{
  public bool IsAlive { get; set; }
}
```

The generated code for the Human property is :
``` 
public global::ProxyInterfaceSourceGeneratorTests.Source.IHuman Human { get => Mapster.TypeAdapter.Adapt<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman>(_Instance.Human); set => _Instance.Human = Mapster.TypeAdapter.Adapt<ProxyInterfaceSourceGeneratorTests.Source.Human>(value); }
```

Which would be changed to support Lazy?

**Comment by JROBOTO** [comment]
Ok just had a deeper look and its not the actual properties but the TypeAdapterConfig being generated in each constructor that is causing it to be slow especially if a class has a lot of subclasses proxied.

In my example. constructing each proxy takes about 4ms however for 15000 objects in total, that adds up

**Comment by StefH** [comment]
I do not understand yet how to build this and if this is possible using mapster.

As a possible quick fix, I've defined the mappings in a static constructor, so it's only executed once.

``` c#
public partial class PersonProxy : global::ProxyInterfaceSourceGeneratorTests.Source.HumanProxy, global::ProxyInterfaceSourceGeneratorTests.Source.IPerson
    {
        static PersonProxy()
        {
            Mapster.TypeAdapterConfig<global::ProxyInterfaceSourceGeneratorTests.Source.Human, global::ProxyInterfaceSourceGeneratorTests.Source.IHuman>.NewConfig().ConstructUsing(instance2145588841 => new global::ProxyInterfaceSourceGeneratorTests.Source.HumanProxy(instance2145588841));
            Mapster.TypeAdapterConfig<global::ProxyInterfaceSourceGeneratorTests.Source.IHuman, global::ProxyInterfaceSourceGeneratorTests.Source.Human>.NewConfig().MapWith(proxy1567394325 => ((global::ProxyInterfaceSourceGeneratorTests.Source.HumanProxy) proxy1567394325)._Instance);

        }

        // . . .

```
https://github.com/StefH/ProxyInterfaceSourceGenerator/pull/76

**Comment by JROBOTO** [comment]
Fair enough, I'm not going to pretend to be an expert in Mapster, in fact my only interaction with it is through your library 😆 
Static constructors sound like they would resolve the issue nicely

**Comment by JROBOTO** [comment]
Not sure what policy you have on who you count as a reviewer on a PR but I have given it a tick

**Comment by StefH** [comment]
I've create a new NuGet (0.3.0) which should be available shortly.

Please test this one, and report back if this helps.

**Comment by JROBOTO** [comment]
That's given us an incredible amount of performance, thanks!!!
