### ISSUE TITLE
Does not support identical class names which have different base classes

### ISSUE THREAD

**Issue by harry0198** [StefH/ProxyInterfaceSourceGenerator#78]
Hi,
I'm currently facing an issue where if you try to create a proxy object for two classes which have the same name and inherit from different objects, the proxy generator can't build.
I.e.: 
```csharp
namespace ProxyInterfaceDemo;

public class Group : Displayable
{
    public string Name { get; set; }
}
```
```csharp
namespace ProxyInterfaceDemo.Depth;

public class Group : Destroyable
{
    
}
```
```csharp
[Proxy(typeof(Displayable), true, ProxyClassAccessibility.Internal)]
public partial interface IDisplayable
{
}

[Proxy(typeof(Destroyable), true, ProxyClassAccessibility.Internal)]
public partial interface IDestroyable
{
}

[Proxy(typeof(Group), ProxyClassAccessibility.Internal)]
public partial interface IGroup : IDisplayable
{
}

[Proxy(typeof(Depth.Group), ProxyClassAccessibility.Internal)]
public partial interface IGroupDepth : IDisplayable
{
}
```

```0>ProxyInterfaceDemo.GroupProxy.g.cs(15,28): Error CS0263 : Partial declarations of 'GroupProxy' must not specify different base classes
0>ProxyInterfaceDemo.GroupProxy.g.cs(15,86): Error CS0738 : 'GroupProxy' does not implement interface member 'IDisplayable._Instance'. 'GroupProxy._Instance' cannot implement 'IDisplayable._Instance' because it does not have the matching return type of 'Displayable'.
0>ProxyInterfaceDemo.GroupProxy.g.cs(15,86): Error CS0535 : 'GroupProxy' does not implement interface member 'IDisplayable.Display()'
0>ProxyInterfaceDemo.Depth.GroupProxy.g.cs(19,59): Error CS0102 : The type 'GroupProxy' already contains a definition for '_Instance'
0>------- Finished building project: ProxyInterfaceDemo. Succeeded: False. Errors: 4. Warnings: 0
Build completed in 00:00:00.976
```

I have created an example of the issue I'm facing at https://github.com/harry0198/ProxyInterfaceDemo
Unclear if I'm creating the proxy objects incorrectly or if this is a bug?

**Comment by StefH** [comment]
Hello @harry0198 .
Some observations from my side:

1. The class Group extends Destroyable, so in that case the IGroupDepth should extend IDestroyable
2. I'm investigating the logic, however placing the IGroupDepth  also in the Depth.Group namespace will also solve your issue




///
https://github.com/StefH/ProxyInterfaceSourceGenerator/pull/79
///

**Comment by harry0198** [comment]
Ah apologies, little typo from me there in the proxy definition. This does still persist when changing the interface to its correct type.
Thank you for the suggestion - moving it into the namespace works great as far as I can tell 👍 I'll keep an eye on your investigations still though

**Comment by StefH** [comment]
If this solves your, then for now I'll close this one and merge the PR with the example.

In the future ; if needed, I can take another look.
